name: CI

on:
  push:
    branches:
      - master
    tags: [ "*" ]
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8 ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6

      - name: Checking Code style
        run: sbt check

      - name: Build and Publish to Local
        run: sbt +publishLocal
  
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8 ]
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Run Test
        if: success() || failure()
        run: sbt coverage test coverageReport

      - name: Aggregate coverage report
        if: success() || failure()
        run: sbt coverageAggregate

      - name: Upload test coverage report
        if: success() || failure()
        run: bash <(curl -s https://codecov.io/bash) 

  ci:
    runs-on: ubuntu-20.04
    needs: [ build, test]
    steps:
      - name: Aggregate outcomes
        run: echo "build succeeded"
        
  publish:
    runs-on: ubuntu-20.04
    needs: [ci]
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.3.0
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v3.9.0
        with:
          distribution: temurin
          java-version: 8
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Release artifacts
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}        
